name: Basic Workflow new

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to print"
        required: true
        default: "Hello World"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "${{ github.event.inputs.message }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Second job
        run: echo "Job 2 completed"
